name: Create release

on:
  workflow_call:
    secrets:
      GH_PAT:
        required: true

jobs:
  create-release:
    name: create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
      - name: get version
        id: vars
        run: |
          #!/bin/bash
          set -eux

          git fetch --tags
          TAG=$(git tag --sort=committerdate | tail -1)

          delimiter=.
          array=($(echo "$TAG" | tr $delimiter '\n'))
          array[$position]=$((array[$position]+1))
          TAG=$(local IFS=$delimiter; echo "${array[*]}")

          if ! git tag | grep "${TAG}"; then
            echo "tag=${TAG}" >> $GITHUB_OUTPUT
          else
            echo "'${TAG}' already exists. No action taken."
            exit 0
          fi

      - name: create release
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "creating release: ${{ steps.vars.outputs.tag }}"
          gh release create ${{ steps.vars.outputs.tag }} --generate-notes
