on: workflow_call

jobs:
  create-release:
    uses: ./.github/workflows/create-release.yaml
    secrets: inherit
  deploy-prd:
    needs:
      - create-release
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: deploy
        run: echo "deployed"
