on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Deploy
jobs:
  should-run:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    steps:
      run: echo "Running..."
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #     - name: Test
  #       run: npm run test
  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy
  #       run: echo "Deploying..."
  bump-version:
    needs:
      - should-run
    #   - test
    #   - deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
      - uses: actions/setup-node@v4
      - name: Bump version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version patch
          git push

  tag-npm-release:
    needs: bump-version
    name: Tag new npm package releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
      - name: create-tag
        run: |
          #!/bin/bash
          set -eux

          TAG="v$(cat package.json | jq -r '.version')"

          # In case only a shallow clone was done
          git fetch --tags

          if ! git tag | grep "${TAG}"; then
            git config user.name github-actions
            git config user.email github-actions@github.com

            git tag -a ${TAG} -m ${TAG}
            git push --follow-tags -f
          else
            echo "'${TAG}' already exists. No action taken."
          fi
