on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Deploy
jobs:
  if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #     - name: Test
  #       run: npm run test
  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy
  #       run: echo "Deploying..."
  bump-version:
    # needs:
    #   - test
    #   - deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        token: ${{ secrets.GH_PAT }}
      - uses: actions/setup-node@v4
      - name: Bump version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version patch
          git push

  tag-npm-release:
    name: Tag new npm package releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: neverendingqs/gh-action-tag-on-npm-version@master
        with:
          token: ${{ secrets.GH_PAT }}
