on: workflow_call

jobs:
  deploy-prd:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/create-release.yaml
      - uses: actions/checkout@v4
      - name: deploy
        run: echo "deployed"
