on: workflow_call

jobs:
  deploy-prd:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: ./.github/workflows/create-release.yaml
        secrets: inherit
      - uses: actions/checkout@v4
      - name: deploy
        run: echo "deployed"
