on:
  pull_request:
    types: [closed]
    branches:
      - main
  push:
    branches:
      - main

name: Deploy
jobs:
  deploy:
    uses: ./.github/workflows/deploy-test-envs.yaml
    secrets: inherit
  create-release:
    needs:
      - deploy
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/create-release.yaml
