on:
  pull_request:
    types: [closed]
    branches:
      - main

name: Deploy
jobs:
  deploy:
    uses: ./.github/workflows/deploy-test-envs.yaml
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
  create-release:
    uses: ./.github/workflows/create-release.yaml
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
