on:
  push:
    branches:
      - main

name: Deploy
jobs:
  deploy:
    uses: ./.github/workflows/deploy-test-envs.yaml
    secrets: inherit
  deploy-prd:
    needs:
      - deploy
    uses: ./.github/workflows/deploy-release.yaml
